PeaLearning.Website/Components/BlogRecentViewComponent.cs
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using PeaLearning.Application.Queries;

namespace PeaLearning.Website.Components
{
    public class BlogRecentViewComponent : BaseViewComponent
    {
        private readonly IMediator _mediator;
        public BlogRecentViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            int limit = 3;
            var courses = await _mediator.Send(new ListLatestBlogQuery(limit));
            return View(courses);
        }
    }
}

PeaLearning.Website/Components/PagingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PeaLearning.Website.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PeaLearning.Website.Components
{
    public class PagingViewComponent : BaseViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PaginationModel pagingInfo)
        {
            int pageNum = (int)Math.Ceiling((double)pagingInfo.Count / pagingInfo.PageSize);
            if (pageNum * pagingInfo.PageSize < pagingInfo.Count)
            {
                pageNum++;
            }
            pagingInfo.LinkSite = pagingInfo.LinkSite.TrimEnd('/') + "/";
            const string buildLink = "<li class='page-item {2}'><a class='page-link' href='{0}{1}' >{3}</a> </li>";
            const string active = "active";
            const string prev_page = "class='prev-page'";
            const string next_page = "class='next-page'";
            const string strTrang = "p";
            string currentPage = pagingInfo.PageIndex.ToString();
            StringBuilder htmlPage = new StringBuilder();
            int iCurrentPage = 0;
            if (pagingInfo.PageIndex <= 0) iCurrentPage = 1;
            else iCurrentPage = pagingInfo.PageIndex;
            if (pageNum <= 3)
            {
                if (pageNum != 1)
                {
                    for (int i = 1; i <= pageNum; i++)
                    {
                        if (i == 1)
                        {
                            htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite.TrimEnd('/'), string.Empty, i == pagingInfo.PageIndex ? active : string.Empty, i);
                        }
                        else
                        {
                            htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + i, i == pagingInfo.PageIndex ? active : string.Empty, i);
                        }
                    }
                }
            }
            else
            {
                if (iCurrentPage == 1)
                {
                    for (int i = 1; i <= 3; i++)
                    {
                        if (i == 1)
                        {
                            htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite.TrimEnd('/'), "", i == pagingInfo.PageIndex ? active : string.Empty, i);
                        }
                        else
                        {
                            htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + i, i == pagingInfo.PageIndex ? active : string.Empty, i);
                        }
                    }
                    htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + 2, next_page, "Next");
                }
                if (iCurrentPage > 1 && iCurrentPage < pageNum)
                {
                    if (iCurrentPage > 1)
                    {
                        if (iCurrentPage - 1 == 1)
                        {
                            htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite.TrimEnd('/'), string.Empty, prev_page, "Prev");
                        }
                        else
                        {
                            htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + (iCurrentPage - 1), prev_page, "Prev");
                        }
                    }
                    for (int i = (iCurrentPage - 1); i <= (iCurrentPage + 1 < pageNum ? iCurrentPage + 1 : pageNum); i++)
                    {
                        if (i > 0)
                        {
                            if (i == 1)
                            {
                                htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite.TrimEnd('/'), "", i == pagingInfo.PageIndex ? active : string.Empty, i);
                            }
                            else
                            {
                                htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + i, i == pagingInfo.PageIndex ? active : string.Empty, i);
                            }
                        }
                    }
                    if (iCurrentPage <= pageNum - 1)
                    {
                        htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + (iCurrentPage + 1), next_page, "Next");
                    }
                }
                int intCurrentPage = 0;
                int.TryParse(currentPage, out intCurrentPage);
                if (intCurrentPage == 0) intCurrentPage = 1;
                if (iCurrentPage == pageNum)
                {
                    htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + (iCurrentPage - 1), prev_page, "Prev");
                    int j = 2;
                    for (int i = pageNum; i >= pageNum - 2; i--)
                    {
                        htmlPage.AppendFormat(buildLink, pagingInfo.LinkSite, strTrang + (pageNum - j), j == 0 ? active : string.Empty, pageNum - j);
                        j--;
                    }
                }
            }
            StringBuilder sb = new StringBuilder();
            sb.AppendFormat("<ul class='pagination justify-content-center mb-0'>{0}</ul>", htmlPage);
            return View("Default",sb.ToString());
        }
    }
}

PeaLearning.Website/Controllers/BlogController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using PeaLearning.Application.Queries;
using PeaLearning.Common.Utils;
using PeaLearning.Website.Models.Common;
using static PeaLearning.Common.Constants;

namespace PeaLearning.Website.Controllers
{
    public class BlogController : BaseController
    {
        private readonly IMediator _mediator;

        public BlogController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("tin-tuc/p{pageIndex}")]
        [Route("tin-tuc")]
        public async Task<IActionResult> Index(int pageIndex = 1)
        {
            int pageSize = 6;
            int skip = (pageIndex - 1) * pageSize;
            var blogs = await _mediator.Send(new ListBlogsQuery(skip, pageSize));
            #region paging
            if (blogs.Count > 0)
            {
                PaginationModel pageModel = new PaginationModel
                {
                    PageIndex = pageIndex,
                    Count = blogs.Count,
                    LinkSite = CoreUtils.GetCurrentURL(Request.Path.ToString(), pageIndex),
                    PageSize = pageSize
                };
                ViewBag.PagingInfo = pageModel;
            }
            #endregion

            ViewBag.TitlePage = SEO.AddTitle(Meta.BlogTitle);
            ViewBag.MetaDescription = SEO.AddMeta("description", Meta.BlogDesc);
            return View(blogs.Items);
        }

        [Route("tin-tuc/{name}-aid{blogId}")]
        public async Task<IActionResult> Detail(Guid blogId)
        {
            var blog = await _mediator.Send(new GetBlogQuery(blogId));          
            return View(blog);
        }
    }
}

PeaLearning.Website/Views/Blog/Detail.cshtml
@model BlogDto
<!-- Hero Start -->
<section class="bg-half d-table w-100" style="background: url('images/1.jpg') center center;">
    <div class="bg-overlay"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 text-center">
                <div class="page-next-level">
                    <h4 class="title text-white title-dark"> @Model.Name </h4>
                    <div class="page-next">
                        <nav aria-label="breadcrumb" class="d-inline-block">
                            <ul class="breadcrumb bg-white rounded shadow mb-0">
                                <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
                                <li class="breadcrumb-item active"><a href="/tin-tuc">Tin tức</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div><!--end col-->
        </div><!--end row-->
    </div> <!--end container-->
</section><!--end section-->
<!-- Hero End -->


<section class="section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="row">
                    <div class="col-md-2 d-none d-md-block">
                        <ul class="list-unstyled text-center sticky-bar social-icon mb-0">
                            <li class="mb-3 h6">Share</li>
                            <li><a href="javascript:void(0)" class="rounded"><i data-feather="facebook" class="fea icon-sm fea-social"></i></a></li>
                            <li><a href="javascript:void(0)" class="rounded"><i data-feather="twitter" class="fea icon-sm fea-social"></i></a></li>
                        </ul><!--end icon-->
                    </div>

                    <div class="col-md-10">
                        @*<p class="text-muted">This is required when, for example, the final text is not yet available. Dummy text is also known as 'fill text'. It is said that song composers of the past used dummy texts as lyrics when writing melodies in order to have a 'ready-made' text to sing with the melody.</p>*@

                        <ul class="list-unstyled d-flex justify-content-between mt-4">
                            @*<li class="list-inline-item user mr-2"><a href="javascript:void(0)" class="text-muted"><i class="mdi mdi-account text-dark"></i> Calvin Carlo</a></li>*@
                            <li class="list-inline-item date text-muted">
                                <i class="mdi mdi-calendar-check text-dark"></i>
                                @Model.CreatedDate.ToString("dd/MM/yyyy")
                            </li>
                        </ul>
                        <img src="@Model.Thumbnail" class="img-fluid rounded-md shadow" alt="">
                        <h5 class="mt-4">@Model.Name</h5>
                        <div class="content-detail">
                            @Html.Raw(Model.Description)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

PeaLearning.Website/Views/Blog/Index.cshtml
@model IEnumerable<BlogDto>
@{
    var pagingInfo = (PeaLearning.Website.Models.Common.PaginationModel)ViewBag.PagingInfo;
}


<!-- Hero Start -->
<section class="bg-half bg-green d-table w-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 text-center">
                <div class="page-next-level">
                    <h4 class="title text-white"> Tin tức </h4>
                    <div class="page-next">
                        <nav aria-label="breadcrumb" class="d-inline-block">
                            <ul class="breadcrumb bg-white rounded shadow mb-0">
                                <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
                                <li class="breadcrumb-item active"><a href="/tin-tuc">Tin tức</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>  <!--end col-->
        </div><!--end row-->
    </div> <!--end container-->
</section><!--end section-->
<!-- Hero End -->
<!-- Shape Start -->
<div class="position-relative">
    <div class="shape overflow-hidden text-white">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<!--Shape End-->
<!-- Blog Start -->
<section class="section">
    <div class="container">
        <div class="row">
            <!-- BLog Start -->
            <div class="col-lg-8 col-md-6">
                <div class="row">
                    @if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <div class="col-lg-6 col-md-12 mb-4 pb-2">
                                <div class="card blog rounded border-0 shadow">
                                    <div class="position-relative">
                                        <img src="@item.AvatarUrl" class="card-img-top rounded-top" alt="@item.Name">
                                        <div class="overlay rounded-top bg-dark"></div>
                                    </div>
                                    <div class="card-body content">
                                        <h5><a href="@item.Link" class="card-title title text-dark">@item.Name</a></h5>
                                        <div class="post-meta d-flex justify-content-between mt-3">
                                            <a href="@item.Link" class="text-muted readmore">Xem thêm <i class="mdi mdi-chevron-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div><!--end col-->
                        }
                    }

                    <!-- PAGINATION START -->
                    @if (pagingInfo != null)
                    {
                        <div class="col-12">
                            @await Component.InvokeAsync("Paging", pagingInfo)
                        </div><!--end col-->
                    }
                    <!-- PAGINATION END -->
                </div><!--end row-->
            </div><!--end col-->
            <!-- BLog End -->
            <!-- START SIDEBAR -->


            @await Component.InvokeAsync("BlogRecent")
           
            <!-- END SIDEBAR -->
        </div><!--end row-->
    </div><!--end container-->
</section><!--end section-->
<!-- Blog End -->