PeaLearning.Website/Models/MyAccount/UserProfileModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PeaLearning.Website.Models.MyAccount
{
    public class UserProfileModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên", AllowEmptyStrings = false)]
        public string FirstName { set; get; }

        [Required(ErrorMessage = "Vui lòng nhập họ", AllowEmptyStrings = false)]
        public string LastName { set; get; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ email")]
        [RegularExpression(@"^[\w+][\w\.\-]+@[\w\-]+(\.\w{2,4})+$", ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string Address { get; set; }


        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        public string PhoneNumber { set; get; }
    }

    public class UserStatisticModel
    {
        public string Email { get; set; }
        public string Phone { get; set; }
        public string DisplayName { get; set; }
        public double Score { get; set; }
        public DateTime UpdatedDate { get; set; }

    }
}

PeaLearning.Website/Components/ProfileHeaderViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PeaLearning.Domain.AggregateModels.UserAggregate;
using PeaLearning.Website.Models.MyAccount;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PeaLearning.Website.Components
{
    public class ProfileHeaderViewComponent : BaseViewComponent
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        public ProfileHeaderViewComponent(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userModel = await _userManager.FindByIdAsync(CurrentUser.Id.ToString());
            UserStatisticModel userStatisticModel = new UserStatisticModel()
            {
                Email = userModel.Email,
                Phone = userModel.PhoneNumber,
                Score = 0,
                UpdatedDate = DateTime.Now,
                DisplayName = userModel.DisplayName
            };
            return View(userStatisticModel);
        }
    }
}

PeaLearning.Website/Components/ProfileStatisticViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PeaLearning.Domain.AggregateModels.UserAggregate;
using PeaLearning.Website.Models.MyAccount;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PeaLearning.Website.Components
{
    public class ProfileStatisticViewComponent : BaseViewComponent
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        public ProfileStatisticViewComponent(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userModel = await _userManager.FindByIdAsync(CurrentUser.Id.ToString());
            UserStatisticModel userStatisticModel = new UserStatisticModel()
            {
                Email = userModel.Email,
                Phone = userModel.PhoneNumber,
                Score = 0,
                UpdatedDate = DateTime.Now,
                DisplayName = userModel.DisplayName
            };
            return View(userStatisticModel);
        }
    }
}

PeaLearning.Website/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PeaLearning.Common.Enumerations;
using PeaLearning.Common.Utils;
using PeaLearning.Domain.AggregateModels.UserAggregate;
using PeaLearning.Website.Extensions;
using PeaLearning.Website.Models;
using PeaLearning.Website.Models.MyAccount;
using Shared.Constants;

namespace PeaLearning.Website.Controllers
{
    [Authorize]
    public class MyAccountController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public MyAccountController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [Route("profile")]
        public async Task<IActionResult> Profile()
        {
            ViewBag.TitlePage = SEO.AddTitle("Thông tin cá nhân");
            var userModel = await _userManager.FindByIdAsync(CurrentUser.Id.ToString());
            UserStatisticModel userStatisticModel = new UserStatisticModel()
            {
                Email = userModel.Email,
                Phone = userModel.PhoneNumber,
                Score = 0,
                UpdatedDate = DateTime.Now,
                DisplayName = userModel.DisplayName
            };
            return View(userStatisticModel);
        }

        [Route("change-profile")]
        public async Task<IActionResult> ChangeProfile()
        {
            ViewBag.TitlePage = SEO.AddTitle("Cập nhật thông tin cá nhân");
            var userModel = await _userManager.FindByIdAsync(CurrentUser.Id.ToString());
            UserProfileModel userProfileModel = new UserProfileModel()
            {
                Address = userModel.Address,
                Email = userModel.Email,
                Id = userModel.Id,
                PhoneNumber = userModel.PhoneNumber,
                FirstName = userModel.FirstName,
                LastName = userModel.LastName
            };
            return View(userProfileModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfile(UserProfileModel model)
        {
            var msg = new CommonResultModel();
            var user = await _userManager.GetUserAsync(HttpContext.User);
            user.Address = model.Address;
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            var updateResult = await _userManager.UpdateAsync(user);
            if (!updateResult.Succeeded)
            {
                msg.NextAction = (int)NextAction.Message;
                msg.Title = "Cập nhật thất bại";
                msg.Error = true;
            }
            else
            {
                msg.NextAction = (int)NextAction.Reload;
                msg.Title = "Cập nhật thành công";
            }
            return Json(msg);
        }
    }
}

PeaLearning.Website/Views/MyAccount/ChangeProfile.cshtml
@using PeaLearning.Website.Models.MyAccount;
@model UserProfileModel
<!-- Hero Start -->
@await Component.InvokeAsync("ProfileHeader")
<!-- Hero End -->
<!-- Profile Start -->
<section class="section mt-60">
    <div class="container mt-lg-3">
        <div class="row">
            @await Component.InvokeAsync("ProfileStatistic")

            <div class="col-lg-8 col-12">
                <div class="card border-0 rounded shadow">
                    <div class="card-body">
                        <h5 class="text-md-left text-center">Thông tin cá nhân</h5>
                        <form asp-controller="MyAccount" asp-action="UpdateProfile" method="post">
                            <input type="hidden" asp-for="Id" />
                            <div class="row mt-4">
                                <div class="col-md-6">
                                    <div class="form-group position-relative">
                                        <label>
                                            Tên
                                        </label>
                                        <i data-feather="user" class="fea icon-sm icons"></i>
                                        <input type="text" asp-for="FirstName" class="form-control pl-5" placeholder="Tên" />
                                        <span class="error" asp-validation-for="FirstName"></span>
                                    </div>
                                </div><!--end col-->

                                <div class="col-md-6">
                                    <div class="form-group position-relative">
                                        <label>Họ</label>
                                        <i data-feather="user-check" class="fea icon-sm icons"></i>
                                        <input type="text" asp-for="LastName" class="form-control pl-5" placeholder="Họ" />
                                        <span class="error" asp-validation-for="LastName"></span>
                                    </div>
                                </div><!--end col-->
                                <div class="col-md-6">
                                    <div class="form-group position-relative">
                                        <label>Email</label>
                                        <i data-feather="mail" class="fea icon-sm icons"></i>
                                        <input type="text" readonly="readonly" asp-for="Email" class="form-control pl-5" placeholder="Email" />
                                        <span class="error" asp-validation-for="Email"></span>
                                    </div>
                                </div><!--end col-->
                                <div class="col-md-6">
                                    <div class="form-group position-relative">
                                        <label>Số điện thoại</label>
                                        <i data-feather="phone" class="fea icon-sm icons"></i>
                                        <input type="text" readonly="readonly"  asp-for="PhoneNumber" class="form-control pl-5" placeholder="Số điện thoại" />
                                        <span class="error" asp-validation-for="PhoneNumber"></span>
                                    </div>
                                </div><!--end col-->
                                <div class="col-md-12">
                                    <div class="form-group position-relative">
                                        <label>Địa chỉ</label>
                                        <i data-feather="map" class="fea icon-sm icons"></i>
                                        <input type="text" asp-for="Address" class="form-control pl-5" placeholder="Địa chỉ" />
                                        <span class="error" asp-validation-for="Address"></span>
                                    </div>
                                </div><!--end col-->
                            </div><!--end row-->
                            <div class="row">
                                <div class="col-md-12">
                                    <div id="lblMessage" class="error"></div>
                                </div>
                                <div class="col-sm-12">
                                    <button id="btnChangeProfile" type="submit" class="btn btn-primary">Submit</button>
                                </div><!--end col-->
                            </div><!--end row-->
                        </form><!--end form-->
                    </div>
                </div>
            </div><!--end col-->

        </div>
    </div>
</section>
<!-- Profile End -->

PeaLearning.Website/Views/MyAccount/Profile.cshtml
@model PeaLearning.Website.Models.MyAccount.UserStatisticModel
<!-- Hero Start -->
@await Component.InvokeAsync("ProfileHeader")
<!-- Hero End -->
<!-- Profile Start -->
<section class="section mt-60">
    <div class="container mt-lg-3">
        <div class="row">
            @await Component.InvokeAsync("ProfileStatistic")

            <partial name="_LessonStatistic" model="@Model" />
        </div>
    </div>
</section>
<!-- Profile End -->

PeaLearning.Website/Views/MyAccount/_LessonStatistic.cshtml
@model PeaLearning.Website.Models.MyAccount.UserStatisticModel

<div class="col-lg-8 col-12">
    <div class="border-bottom pb-4">
        <h5>Krista Joseph</h5>
        <p class="text-muted mb-0">I have started my career as a trainee and prove my self and achieve all the milestone with good guidance and reach up to the project manager. In this journey, I understand all the procedure which make me a good developer, team leader, and a project manager.</p>
    </div>

    <div class="border-bottom pb-4">
        <div class="row">
            <div class="col-md-6 mt-4">
                <h5>Personal Details :</h5>
                <div class="mt-4">
                    <div class="media align-items-center">
                        <i data-feather="mail" class="fea icon-ex-md text-muted mr-3"></i>
                        <div class="media-body">
                            <h6 class="text-primary mb-0">Email :</h6>
                            <a href="javascript:void(0)" class="text-muted">kristajoseph0203@mail.com</a>
                        </div>
                    </div>
                    <div class="media align-items-center mt-3">
                        <i data-feather="phone" class="fea icon-ex-md text-muted mr-3"></i>
                        <div class="media-body">
                            <h6 class="text-primary mb-0">Cell No :</h6>
                            <a href="javascript:void(0)" class="text-muted">(+12) 1254-56-4896</a>
                        </div>
                    </div>
                </div>
            </div><!--end col-->

            <div class="col-md-6 mt-4 pt-2 pt-sm-0">
                <h5>Danh sách khóa học:</h5>

                @*<div class="media key-feature align-items-center p-3 rounded shadow mt-4">
                    <img src="/Images/job/Circleci.svg" class="avatar avatar-ex-sm" alt="">
                    <div class="media-body content ml-3">
                        <h4 class="title mb-0">Senior Web Developer</h4>
                        <p class="text-muted mb-0">3 Years Experience</p>
                        <p class="text-muted mb-0"><a href="javascript:void(0)" class="text-primary">CircleCi</a> London, UK</p>
                    </div>
                </div>

                <div class="media key-feature align-items-center p-3 rounded shadow mt-4">
                    <img src="/Images/job/Codepen.svg" class="avatar avatar-ex-sm" alt="">
                    <div class="media-body content ml-3">
                        <h4 class="title mb-0">Web Designer</h4>
                        <p class="text-muted mb-0">2 Years Experience</p>
                        <p class="text-muted mb-0"><a href="javascript:void(0)" class="text-primary">Codepen</a> Washington D.C, USA</p>
                    </div>
                </div>

                <div class="media key-feature align-items-center p-3 rounded shadow mt-4">
                    <img src="/Images/job/Gitlab.svg" class="avatar avatar-ex-sm" alt="">
                    <div class="media-body content ml-3">
                        <h4 class="title mb-0">UI Designer</h4>
                        <p class="text-muted mb-0">2 Years Experience</p>
                        <p class="text-muted mb-0"><a href="javascript:void(0)" class="text-primary">Gitlab</a> Perth, Australia</p>
                    </div>
                </div>*@


            </div><!--end col-->
        </div><!--end row-->
    </div>

</div><!--end col-->

PeaLearning.Website/Views/MyAccount/_ProfileStatistic.cshtml
@model PeaLearning.Website.Models.MyAccount.UserStatisticModel

<div class="col-lg-4 col-md-6 col-12 d-lg-block d-none">
    <div class="sidebar sticky-bar p-4 rounded shadow">
        <div class="widget">
            <h5 class="widget-title">Điểm của tôi :</h5>
            <div class="row mt-4">
                <div class="col-6 text-center">
                    <i data-feather="user-plus" class="fea icon-ex-md text-primary mb-1"></i>
                    <h5 class="mb-0">@Model.Score</h5>
                    <p class="text-muted mb-0">điểm</p>
                </div><!--end col-->
            </div><!--end row-->
        </div>

        <div class="widget mt-4 pt-2">
            <h5 class="widget-title">Khóa học :</h5>
            <div class="progress-box mt-4">
                <h6 class="title text-muted">Progress</h6>
                <div class="progress">
                    <div class="progress-bar position-relative bg-primary" style="width:50%;">
                        <div class="progress-value d-block text-muted h6">50 / 100</div>
                    </div>
                </div>
            </div><!--end process box-->
        </div>

        <div class="widget">
            <div class="row">
                <div class="col-6 mt-4 pt-2">
                    <a href="/profile" class="accounts active rounded d-block shadow text-center py-3">
                        <span class="pro-icons h3 text-muted"><i class="uil uil-dashboard"></i></span>
                        <h6 class="title text-dark h6 my-0">Profile</h6>
                    </a>
                </div><!--end col-->
                <div class="col-6 mt-4 pt-2">
                    <a href="/change-profile" class="accounts rounded d-block shadow text-center py-3">
                        <span class="pro-icons h3 text-muted"><i class="uil uil-users-alt"></i></span>
                        <h6 class="title text-dark h6 my-0">Members</h6>
                    </a>
                </div><!--end col-->
                <div class="col-6 mt-4 pt-2">
                    <a href="/dang-xuat" class="accounts rounded d-block shadow text-center py-3">
                        <span class="pro-icons h3 text-muted"><i class="uil uil-sign-out-alt"></i></span>
                        <h6 class="title text-dark h6 my-0">Logout</h6>
                    </a>
                </div>
                @*

                    <div class="col-6 mt-4 pt-2">
                        <a href="account-works.html" class="accounts rounded d-block shadow text-center py-3">
                            <span class="pro-icons h3 text-muted"><i class="uil uil-file"></i></span>
                            <h6 class="title text-dark h6 my-0">Works</h6>
                        </a>
                    </div>

                    <div class="col-6 mt-4 pt-2">
                        <a href="account-messages.html" class="accounts rounded d-block shadow text-center py-3">
                            <span class="pro-icons h3 text-muted"><i class="uil uil-envelope-star"></i></span>
                            <h6 class="title text-dark h6 my-0">Messages</h6>
                        </a>
                    </div>

                    <div class="col-6 mt-4 pt-2">
                        <a href="account-payments.html" class="accounts rounded d-block shadow text-center py-3">
                            <span class="pro-icons h3 text-muted"><i class="uil uil-transaction"></i></span>
                            <h6 class="title text-dark h6 my-0">Payments</h6>
                        </a>
                    </div>

                    <div class="col-6 mt-4 pt-2">
                        <a href="account-setting.html" class="accounts rounded d-block shadow text-center py-3">
                            <span class="pro-icons h3 text-muted"><i class="uil uil-setting"></i></span>
                            <h6 class="title text-dark h6 my-0">Settings</h6>
                        </a>
                    </div>

                    <div class="col-6 mt-4 pt-2">
                        <a href="auth-login-three.html" class="accounts rounded d-block shadow text-center py-3">
                            <span class="pro-icons h3 text-muted"><i class="uil uil-sign-out-alt"></i></span>
                            <h6 class="title text-dark h6 my-0">Logout</h6>
                        </a>
                    </div>*@
            </div><!--end row-->
        </div>

    </div>
</div>